In [2]:
!pip install torch

In [5]:
import torch

## Introduction to tensor

In [28]:
## tensor = multidimensional array similar to numpy
### Built in tensor
print("Empty tensor\n",torch.empty(2,3))
print("Zeros tensor\n",torch.zeros(2,3))
print("random tensor\n",torch.rand(2,3))
print("Ones tensor\n",torch.ones(2,3))
print("identity matrix",torch.eye(2,3)) # n=2,m=3
seed = torch.manual_seed(1000)
print("to get reproducibility:",)
print("random tensor 1 \n",torch.rand(2,3))
print("random tensor 2 \n",torch.rand(2,3))

Empty tensor
 tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4153e-43, 5.6052e-45]])
Zeros tensor
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
random tensor
 tensor([[0.4217, 0.1254, 0.6818],
        [0.0571, 0.6818, 0.0473]])
Ones tensor
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
identity matrix tensor([[1., 0., 0.],
        [0., 1., 0.]])
to get reproducibility:
random tensor 1 
 tensor([[0.3189, 0.6136, 0.4418],
        [0.2580, 0.2724, 0.6261]])
random tensor 2 
 tensor([[0.4410, 0.3653, 0.3535],
        [0.5971, 0.3572, 0.4807]])


In [13]:
# dtype
a = torch.tensor(1)
type(a)

torch.Tensor

In [18]:
## custom tensor
a = torch.tensor([1,2,3])
print("Custom tensor:\n",a)
# 1. zero dimensional tensor
zero = torch.tensor(1)
print("Dimension:",zero.dim())
# 2. One dimension tensor
one = torch.tensor([1,2,3])
print("Dimension:",one.dim())
# 3. two dimension tensor
two = torch.tensor([[1,2,3],[1,2,3]])
print("Dimension:",two.dim())
# 4. three dimension tensor
three = torch.tensor([[[1,2,3],[1,2,3],[1,2,3]]])
print("Dimension:",three.dim())
## so on

Custom tensor:
 tensor([1, 2, 3])
Dimension: 0
Dimension: 1
Dimension: 2
Dimension: 3


In [22]:
## Changing the tensor datatype
a = torch.tensor([1,2,3,4])
print("type",a.dtype)
a = a.to(torch.float32)
print("type",a.dtype)

type torch.int64
type torch.float32


In [25]:
## Coping the tensor
a = torch.tensor([1,2,3])
b = a
b[0] = 4
print(a,b) ## the changes are reflected

tensor([4, 2, 3]) tensor([4, 2, 3])


In [27]:
a = torch.tensor([1,2,3])
b = a.clone()
b[0] = 4
print(a,b) ## not changing

tensor([1, 2, 3]) tensor([4, 2, 3])


In [29]:
## arithematic operation on tensor with constant
a = torch.tensor([[1,2,3],[4,5,6]])
print("location wise addition:",2+a)
print("scaling",2*a)
print("dividing",a/4)

location wise addition: tensor([[3, 4, 5],
        [6, 7, 8]])
scaling tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
dividing tensor([[0.2500, 0.5000, 0.7500],
        [1.0000, 1.2500, 1.5000]])


In [30]:
## arithematic operation on tensor with other tensor
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[1,2,3],[4,5,6]])
print("Addition:",a+b)
print("Substraction:",a-b)
print("Multplication:",a*b)
print("Division",a/b)
print("Power operation",a**b)

Addition: tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
Substraction: tensor([[0, 0, 0],
        [0, 0, 0]])
Multplication: tensor([[ 1,  4,  9],
        [16, 25, 36]])
Division tensor([[1., 1., 1.],
        [1., 1., 1.]])
Power operation tensor([[    1,     4,    27],
        [  256,  3125, 46656]])


In [ ]:
## tensor operation to get GPU
# to check cuda
print(torch.cuda.is_available())
# to set gpu
device = torch.device("cuda")
print(device)
# Creating on GPU
torch.tensor([1,2,3],device=device)
## moving cpu to gpu
b = torch.tensor([1,2,3])
a = b.to(device)

In [33]:
## Reshaping the tensor
### Note:= while reshaping just get the multpilcation of new tensor(all shape) is equal to previous tensor(all shape)
a = torch.rand(4,4) # 4x4 = 16
print("Tensor\n:",a)
print("Shape:",a.shape)
print("reshaped tensor:\n",a.reshape(2,2,2,2)) # 2x2x2x2 = 16
print("Shape:",a.reshape(2,2,2,2).shape)

Tensor
: tensor([[0.9472, 0.6221, 0.9119, 0.0354],
        [0.6405, 0.3749, 0.9871, 0.7825],
        [0.8949, 0.7395, 0.2569, 0.1575],
        [0.0148, 0.6573, 0.8463, 0.8787]])
Shape: torch.Size([4, 4])
reshaped tensor:
 tensor([[[[0.9472, 0.6221],
          [0.9119, 0.0354]],

         [[0.6405, 0.3749],
          [0.9871, 0.7825]]],


        [[[0.8949, 0.7395],
          [0.2569, 0.1575]],

         [[0.0148, 0.6573],
          [0.8463, 0.8787]]]])
Shape: torch.Size([2, 2, 2, 2])


In [34]:
## flatten the tensor
torch.rand(3,3).flatten()

tensor([0.5838, 0.3050, 0.4746, 0.0229, 0.6680, 0.5553, 0.0865, 0.4258, 0.6251])

In [39]:
## Unsqeeze = adding one dimensional to selected position
### application = adding the batch while image processing and testing in CNN
image = torch.rand(256,256,3)
print("Image shape:",image.shape)
print("at zero positon",torch.unsqueeze(image,0).shape)
print("at one positon",torch.unsqueeze(image,1).shape)

Image shape: torch.Size([256, 256, 3])
at zero positon torch.Size([1, 256, 256, 3])
at one positon torch.Size([256, 1, 256, 3])


In [42]:
## Squeeze to remove any dimension
image = torch.rand(1,20)
print("Image shape:",image.shape)
torch.squeeze(image,0).shape

Image shape: torch.Size([1, 20])


torch.Size([20])

In [46]:
## permute : Some permutation on the tensor
a = torch.rand(2,3,4)
## 0 | 1 | 2 = index of shape
## 2 | 3 | 4 = shape id of
b = a.permute(1,2,0) # shape = (3,4,2)
print(b.shape)

torch.Size([3, 4, 2])
