In [1]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [2]:
! pip install nltk

In [3]:
import torch 
import torch.nn as nn
import torch.optim as optim 
import numpy as np
import nltk
from collections import Counter
from torch.utils.data import Dataset,DataLoader
from nltk.tokenize import word_tokenize

In [4]:
## Tokenization 
nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [6]:
## tokenize
tokens = word_tokenize(faqs.lower())

In [7]:
## building vocabulary 
vocab = {"<unk>":0}

#Counter(tokens) # unique token and tell the word unique value 
for token in Counter(tokens).keys():
    if (token not in vocab):
        vocab[token] = len(vocab)

In [9]:
len(vocab)

289

In [12]:
# extract sentences from data 
input_sentences = faqs.split("\n")

In [17]:
def text_to_indices(sentence,vocab):
    numerical_sentence = []
    for token in sentence:
        if token in vocab:
            numerical_sentence.append(vocab[token])
        else:
            numerical_sentence.append(vocab["<unk>"])
    return numerical_sentence
            

In [19]:
## input sentences to number 
input_numerical_sentences = []
for sentence in input_sentences:
    input_numerical_sentences.append(
        text_to_indices(word_tokenize(sentence.lower()),vocab)
    )

In [21]:
input_numerical_sentences[:10]

[[1, 2, 3],
 [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14, 15],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28, 29, 30],
 [4, 5, 2, 31, 32, 27, 2, 6, 33],
 [2,
  31,
  32,
  27,
  2,
  6,
  5,
  34,
  35,
  30,
  36,
  2,
  31,
  6,
  7,
  37,
  38,
  39,
  34,
  40,
  28,
  41,
  12,
  42,
  30,
  15],
 [4, 5, 2, 43, 27, 2, 11, 3, 33],
 [44, 45, 46, 47, 2, 48, 49, 50],
 [51, 52],
 [51, 53, 8, 9, 10],
 [9, 54]]

In [22]:
len(input_numerical_sentences)

78

In [24]:
## lets build the training sequences 
training_sequence = []
for sentence in input_numerical_sentences:
    for i in range(1,len(sentence)):
        training_sequence.append(sentence[:i+1])

In [26]:
len(training_sequence)

942

In [28]:
## lets padd it 
len_list = [len(seq) for seq in training_sequence]
max(len_list)

62

In [29]:
padded_sequence = []
for seq in training_sequence:
    padded_sequence.append([0]*(max(len_list)-len(seq)) + seq)

In [30]:
padded_sequence[0]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2]

In [31]:
padded_sequence = torch.tensor(padded_sequence,dtype=torch.long)

In [32]:
X = padded_sequence[:,:-1]
y = padded_sequence[:,-1]

In [33]:
X[0],y[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

In [34]:
class CustomDataset(Dataset):
    def __init__(self,X,y):
        self.X = X
        self.y = y
    def __len__(self):
        return self.X.shape[0]
    def __getitem__(self,index):
        return self.X[index],self.y[index]

In [35]:
dataset = CustomDataset(X,y)

In [36]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

In [37]:
dataloader = DataLoader(dataset,batch_size=32,shuffle=True)

In [39]:
for batch,label in dataloader:
    print(batch,label)
    print(batch.shape,label.shape)
    break

tensor([[  0,   0,   0,  ...,  86, 141,   2],
        [  0,   0,   0,  ..., 146,  24,  25],
        [  0,   0,   0,  ...,  35, 142, 151],
        ...,
        [  0,   0,   0,  ...,   2, 175,  78],
        [  0,   0,   0,  ...,  73,  22,  23],
        [  0,   0,   0,  ...,  65,  86, 135]]) tensor([  3,   2, 152,  65, 100,  15,  80,  17,  19, 212,  38,   2,  33, 200,
        120, 199,  53,  30, 180,   8, 149, 228, 131, 183,  99, 194, 246, 142,
         44,   4, 131,  76])
torch.Size([32, 61]) torch.Size([32])


In [51]:
## lets test the model
class LSTMmodel(nn.Module):
    def __init__(self,vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size,100)
        self.lstm = nn.LSTM(100,150,batch_first=True)
        self.fc = nn.Linear(150,vocab_size)
    def forward(self,X):
        embedded = self.embedding(X)
        intermidiate_hidden_state,(final_hidden_state,final_cell_state) = self.lstm(embedded)
        output = self.fc(final_hidden_state.squeeze(0))
        return output

In [52]:
device = "cuda" if torch.cuda.is_available() else "cpu"
model = LSTMmodel(len(vocab)).to(device)

In [53]:
epochs = 50
learning_rate = 0.01
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr=learning_rate)

In [54]:
for epoch in range(epochs):
    total_loss = 0
    for batch_x,batch_y in dataloader:
        batch_x,batch_y = batch_x.to(device),batch_y.to(device)
        optimizer.zero_grad()
        outputs = model(batch_x)
        loss = criterion(outputs,batch_y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch:{epoch+1},Loss:{total_loss:.4f}")

Epoch:1,Loss:152.8963
Epoch:2,Loss:98.6257
Epoch:3,Loss:56.8586
Epoch:4,Loss:30.4845
Epoch:5,Loss:19.1782
Epoch:6,Loss:13.6631
Epoch:7,Loss:9.7911
Epoch:8,Loss:7.5612
Epoch:9,Loss:6.3746
Epoch:10,Loss:5.5191
Epoch:11,Loss:4.9334
Epoch:12,Loss:4.8554
Epoch:13,Loss:4.6536
Epoch:14,Loss:5.1474
Epoch:15,Loss:4.7462
Epoch:16,Loss:4.3649
Epoch:17,Loss:4.1622
Epoch:18,Loss:4.0431
Epoch:19,Loss:3.8945
Epoch:20,Loss:3.8581
Epoch:21,Loss:4.2622
Epoch:22,Loss:4.1127
Epoch:23,Loss:4.3182
Epoch:24,Loss:3.7946
Epoch:25,Loss:3.9374
Epoch:26,Loss:3.9717
Epoch:27,Loss:3.8913
Epoch:28,Loss:3.9092
Epoch:29,Loss:3.9806
Epoch:30,Loss:3.6669
Epoch:31,Loss:3.6633
Epoch:32,Loss:3.8863
Epoch:33,Loss:4.0540
Epoch:34,Loss:3.8313
Epoch:35,Loss:3.6750
Epoch:36,Loss:3.7147
Epoch:37,Loss:3.8316
Epoch:38,Loss:3.7977
Epoch:39,Loss:3.6233
Epoch:40,Loss:3.6327
Epoch:41,Loss:3.7444
Epoch:42,Loss:3.9890
Epoch:43,Loss:3.7276
Epoch:44,Loss:3.6423
Epoch:45,Loss:3.4905
Epoch:46,Loss:3.7437
Epoch:47,Loss:3.7297
Epoch:48,Loss:3

In [60]:
# make prediction 
def prediction(model,vocab,sentence):
    tokenized_sentence = word_tokenize(sentence.lower())
    numerical_text = text_to_indices(tokenized_sentence,vocab)
    padding = [0]*(61-len(numerical_text)) + numerical_text
    padding = torch.tensor(padding,dtype=torch.long).to(device).unsqueeze(0)
    output = model(padding)
    _,index = torch.max(output,1)
    return sentence + " " + list(vocab.keys())[index]
    

In [61]:
prediction(model,vocab,"The Course follows")

'The Course follows a'

In [64]:
input = "The Course follows"
for i in range(10):
    output = prediction(model,vocab,input)
    print(output)
    input = output

The Course follows a
The Course follows a monthly
The Course follows a monthly subscription
The Course follows a monthly subscription model
The Course follows a monthly subscription model where
The Course follows a monthly subscription model where you
The Course follows a monthly subscription model where you have
The Course follows a monthly subscription model where you have to
The Course follows a monthly subscription model where you have to make
The Course follows a monthly subscription model where you have to make monthly
